version: "3.9"

services:
  cnterra-mongo:
    image: mongo:4.4
    container_name: cnterra-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: cnterra
      MONGO_INITDB_ROOT_PASSWORD: cnterra
    volumes:
      - cnterra-vol-mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - cnterra-net

  cnterra-rabbitmq:
    image: rabbitmq:3.10
    container_name: cnterra-rabbitmq
    restart: always
    ports:
      - 5672:5672
    networks:
      - cnterra-net

volumes:
  cnterra-vol-mongo:
    name: cnterra-vol-mongo

networks:
  cnterra-net:
    name: cnterra-net
