CREATE TABLE IF NOT EXISTS FILES (
  ID         UUID PRIMARY KEY,
  NAME       TEXT NOT NULL,
  CONTENT    TEXT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT now(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT now()
);
