CREATE TABLE IF NOT EXISTS NODES (
  ID         UUID PRIMARY KEY,
  NODEID     INT NOT NULL,
  MODEL      TEXT NOT NULL,
  ENABLED    BOOLEAN NOT NULL,
  ATTRIBUTES JSON NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT now(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT now()
);